backend:
  name: git-gateway
  repo: "ZekeriyaAY/blog.zekeriyaay.com" # Path to your GitHub repository. For forked repository, use "your-username/your-repo-name"
  branch: mainBook # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow # for drafting, reviewing, and approving content

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "preview/posts/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "docs"
    label: "Docs"
    folder: "docs/"
    create: true
    slug: "{{slug}}"
    preview_path: "preview/docs/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Weight", name: "weight", widget: "number", default: 0}
      - {label: "Book Flat Section", name: "bookFlatSection", widget: "boolean", default: false}
      - {label: "Book Collapse Section", name: "bookCollapseSection", widget: "boolean", default: false}
      - {label: "Book Hidden", name: "bookHidden", widget: "boolean", default: false}
      - {label: "Book Toc", name: "bookToc", widget: "boolean", default: true}
